### ISSUE TITLE
Build won't work if checked out using SVN

### ISSUE THREAD

**Issue by ocmasong** [jasonwhite/pepatch#13]
Downloaded trunk using SVN, but prebuild step fails to generate "version.h" if repository is not a GIT one. Using GIT worked fine.

**Comment by jasonwhite** [comment]
Just curious -- why do you need to use SVN to clone this repository?

I embed the Git commit SHA into the built executable. This makes it easy to tell the exact source code that was used to build an executable.

**Comment by ocmasong** [comment]
Hi Jason, SVN is the tool I use at work, together with the rare RTC, so it was my first option. We don't use Git right now. Anyway, I managed to do the checkout from Eclipse and build it from MSVC15.

I guess SVN option is provided by GitHub, not you. Maybe just warning potential users they should not do checkout through SVN will avoid them having the same build issues I did.

Oscar.

**Comment by jasonwhite** [comment]
> SVN is the tool I use at work, together with the rare RTC

Yikes! I know from first-hand experience that switching a company away from an old version control system is rather difficult (but very much worth it). However, I don't see how this prevents you from installing Git on your machine and using it.

> Maybe just warning potential users they should not do checkout through SVN will avoid them having the same build issues I did.

There is a bit about Git being required to build at https://github.com/jasonwhite/ducible#building-it.

I'll add more details about how to clone the repository in the README. I figured that anybody using GitHub would also be using Git.
