### ISSUE TITLE
Known Limitations - Digitally Signed Executable

### ISSUE THREAD

**Issue by rweber89** [jasonwhite/pepatch#15]
Hello I have a problem. We have the original .exe and .pdb file of an application we released - that was digitally signed due to being released to customer desktops. Now the application randomly crashed and we have a dump file from the crash.

Now my question is does that mean there is no way for us to look at the dump file because the exe was digitally signed or is there some way around this with the help of your tool or in general?

**Comment by jasonwhite** [comment]
Digitally signing an EXE (with signtool) doesn't prevent being able to debug a crash dump, so I'm not sure what problem you're having. You can also always use `signtool remove /s foo.exe` to remove the digital signature(s).

**Comment by rweber89** [comment]
We digitially signed an EXE, the code generates dumpfiles if it crashes. The signed EXE does not match the PDB file. Since the signing seems to invalidate it. So we cannot examine the DMP file because the DMP is from the signed EXE which does not match the PDB. Does this make sense?

We are using kSign and we are digitally signing the EXE due to Windows ... it's delivered to consumers and Windows blocks unsigned executables.

**Comment by jasonwhite** [comment]
I don't know what kSign does, but I know that `signtool` doesn't change the PDB signature within the PE file.

Closing as this seems unrelated to Ducible.
